### ISSUE TITLE
Take over GitHub Action `rust-action`

### ISSUE THREAD

**Issue by icepuma** [icepuma/rust-action#2]
I'm looking for a person, who would like to take over this GitHub action.

Best regards
Stefan

**Comment by Ganster08** [comment]
Hola

**Comment by Ganster08** [comment]
Hola

**Comment by Mirlahiji** [comment]
Hello Stefan, How’s it going?
I am writing to you in connection with that I would like take over this GitHub action.
I look forward to hearing from you. Thank you in advance.

Sincerely
Delaram

**Comment by icepuma** [comment]
Hey both of you. I will see if I can find out how to deprecate my action and the easiest step would be to create a fork and I will add the fork to the repo to use it instead of my action :)

**Comment by icepuma** [comment]
Okay, so no info right now on how to deprecate the action :/

Therefore, feel free to create a fork. The first one will appear in my README.md :)

Best regards

**Comment by icepuma** [comment]
What do you mean? I think you could just rename the action, publish it under the new name and you're set.

**Comment by D2Machine** [comment]
oh... yes you right 👍🏻

**Comment by icepuma** [comment]
* I did update the readme
* I will archive the project in some days
* Big thank you for taking over the action :)
